---
worker:
  hosts:
    p2-kube-w1:
      ansible_host: 192.168.146.51
      ansible_port: 8933
      disk:
        mount_sizes:
          - /: 20.56 GB
          - /boot: 1.44 GB
          - /var: 13.73 GB
          - /home: 3.86 GB
          - /var/log: 2.88 GB
        lvm:
          lvs:
            lv-home:
              size_g: '4.00'
              vg: vg-home
            lv-root:
              size_g: '20.99'
              vg: vg-root
            lv-var:
              size_g: '13.99'
              vg: vg-var
            lv-varlog:
              size_g: '3.00'
              vg: vg-varlog
          pvs:
            /dev/sda3:
              size_g: '8.00'
              vg: vg-root
            /dev/sda4:
              size_g: '2.00'
              vg: vg-var
            /dev/sda5:
              size_g: '3.00'
              vg: vg-varlog
            /dev/sda6:
              size_g: '4.00'
              vg: vg-home
            /dev/sda7:
              size_g: '12.00'
              vg: vg-var
            /dev/sda8:
              size_g: '13.00'
              vg: vg-root
          vgs:
            vg-home:
              num_lvs: '1'
              num_pvs: '1'
              size_g: '4.00'
            vg-root:
              num_lvs: '1'
              num_pvs: '2'
              size_g: '20.99'
            vg-var:
              num_lvs: '1'
              num_pvs: '2'
              size_g: '13.99'
            vg-varlog:
              num_lvs: '1'
              num_pvs: '1'
              size_g: '3.00'
      network:
        netmask: 28
        gateway: 192.168.146.49
      resource:
        vcpu: 4
        memory: 7957
    p2-kube-w2:
      ansible_host: 192.168.146.51
      ansible_port: 8933
      disk:
        mount_sizes:
          - /: 20.56 GB
          - /boot: 1.44 GB
          - /var: 13.73 GB
          - /home: 3.86 GB
          - /var/log: 2.88 GB
        lvm:
          lvs:
            lv-home:
              size_g: '4.00'
              vg: vg-home
            lv-root:
              size_g: '20.99'
              vg: vg-root
            lv-var:
              size_g: '13.99'
              vg: vg-var
            lv-varlog:
              size_g: '3.00'
              vg: vg-varlog
          pvs:
            /dev/sda3:
              size_g: '8.00'
              vg: vg-root
            /dev/sda4:
              size_g: '2.00'
              vg: vg-var
            /dev/sda5:
              size_g: '3.00'
              vg: vg-varlog
            /dev/sda6:
              size_g: '4.00'
              vg: vg-home
            /dev/sda7:
              size_g: '12.00'
              vg: vg-var
            /dev/sda8:
              size_g: '13.00'
              vg: vg-root
          vgs:
            vg-home:
              num_lvs: '1'
              num_pvs: '1'
              size_g: '4.00'
            vg-root:
              num_lvs: '1'
              num_pvs: '2'
              size_g: '20.99'
            vg-var:
              num_lvs: '1'
              num_pvs: '2'
              size_g: '13.99'
            vg-varlog:
              num_lvs: '1'
              num_pvs: '1'
              size_g: '3.00'
      network:
        netmask: 28
        gateway: 192.168.146.49
      resource:
        vcpu: 4
        memory: 7957