change_kaspersky_state: false
timesyncd_server: 192.168.170.200
pip_repo: "https://repo.asax.ir/repository/pypi-group1/simple"

access_check_single: "test-host:8080"

local_access_list:
  groups:
    - name: master
      ports:
        - 8933
        - 6443
    - name: worker
      ports:
        - 8933
        - 80
        - 443
  singles:
    - name: gitops.asax.ir
      ports:
        - 443
    - name: repo.asax.ir
      ports:
        - 80
        - 443
    - name: azure.asax.ir
      ports:
        - 80
        - 443