access_list:
  groups:
    - name: worker
      ports:
        - 8933
        - 10250
        # - 4789/UDP
  singles:
    - name: gitops.asax.ir
      ports:
        - 443
    - name: repo.asax.ir
      ports:
        - 80
        - 443
    - name: azure.asax.ir
      ports:
        - 80
        - 443