access_list:
  groups:
    - name: master
      ports:
        - 6443
        # - 4789/UDP
        - 10250
  singles:
    - name: gitops.asax.ir
      ports:
        - 443
    - name: repo.asax.ir
      ports:
        - 80
        - 443
    - name: azure.asax.ir
      ports:
        - 80
        - 443
    - name: 172.28.57.10 # Splunk management port
      ports:
        - 8089
    - name: cliq.zoho.com
      ports:
        - 443